import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Search, Bell, ChevronDown, ChevronRight, PanelLeftClose, PanelLeftOpen, Home, Users, CalendarDays, Wallet, TrendingUp, GraduationCap, Settings, FileText, Clock3, CircleHelp, AlertTriangle, CheckCircle2, LockKeyhole, ArrowUpRight, Menu as MenuIcon, X } from 'lucide-react'
import './styles.css'

// 메뉴는 정책 협의용 1차 후보입니다. 고객 확정 메뉴 트리로 오인하지 않도록 표시합니다.
const groups = [
 { id:'home', label:'홈', icon:Home, items:[{id:'dashboard',label:'HR 대시보드',status:'PARTIAL',desc:'개인별 현황과 주요 메뉴로 이동하는 시작 화면',type:'dashboard'}] },
 { id:'people', label:'인사관리', icon:Users, items:[
  {id:'employee',label:'임직원 기본정보',status:'PARTIAL',desc:'임직원 기준정보 화면 구성 검토',type:'grid'},
  {id:'organization',label:'조직·직책 관리',status:'HOLD',desc:'조직·직책 체계 및 적용일자 기준 확인 필요'},
  {id:'appointment',label:'인사발령',status:'HOLD',desc:'발령 유형, 승인 절차, 소급 적용 기준 확인 필요'},
  {id:'recruit',label:'채용관리',status:'UNKNOWN',desc:'채용 업무 범위 및 현행 시스템 연계 기준 확인 필요'}] },
 { id:'attendance', label:'근태관리', icon:CalendarDays, items:[
  {id:'attendance-status',label:'근태현황 조회',status:'PARTIAL',desc:'화면 및 조회 조건 확인용 샘플 화면',type:'grid'},
  {id:'work-rule',label:'근무규칙·일정',status:'HOLD',desc:'교대패턴, 근무일정 생성 규칙 및 예외 기준 확인 필요'},
  {id:'leave',label:'연차·휴가 관리',status:'HOLD',desc:'연차 발생·사용·정산 Formula와 적용 기준 확인 필요'},
  {id:'attendance-close',label:'근태 집계·마감',status:'HOLD',desc:'집계 기준, 마감 Snapshot 및 재마감 정책 확인 필요'},
  {id:'leave-promotion',label:'연차촉진',status:'HOLD',desc:'대상자 산정, 통지 시점·문안·수령 증빙 기준 확인 필요'},
  {id:'time-device',label:'타각·외부연계',status:'UNKNOWN',desc:'연계 계약, 이벤트 식별자, 실패·재시도 기준 확인 필요'}] },
 { id:'payroll', label:'급여관리', icon:Wallet, items:[
  {id:'payroll-view',label:'급여 조회',status:'HOLD',desc:'급여정보 접근 범위 및 마스킹 정책 확인 필요'},
  {id:'payroll-calc',label:'급여 계산·마감',status:'HOLD',desc:'급여 Formula, 항목 Mapping, PayRun 및 마감 정책 확인 필요'},
  {id:'payroll-attendance',label:'근태→급여 반영',status:'HOLD',desc:'수량·금액 Authority, 중복반영 및 반영취소 기준 확인 필요'},
  {id:'year-end',label:'연말정산',status:'UNKNOWN',desc:'업무 범위 및 관련 시스템·법정 기준 적용 방안 확인 필요'}] },
 { id:'performance', label:'성과평가', icon:TrendingUp, items:[
  {id:'evaluation-cycle',label:'평가 운영·대상자',status:'UNKNOWN',desc:'평가 주기, 대상자, 단계별 권한과 일정 확인 필요'},
  {id:'evaluation-form',label:'목표·역량평가',status:'UNKNOWN',desc:'평가 항목, 가중치, 등급 산식 및 예외 기준 확인 필요'},
  {id:'evaluation-result',label:'종합평가 결과',status:'HOLD',desc:'등급 산정·조정 권한 및 민감정보 열람 범위 확인 필요'}] },
 { id:'learning', label:'교육관리', icon:GraduationCap, items:[
  {id:'course',label:'교육과정·강사',status:'UNKNOWN',desc:'교육과정 등록·승인 및 강사 관리 범위 확인 필요'},
  {id:'enrollment',label:'수강신청·이력',status:'UNKNOWN',desc:'신청·취소·승인·수료 처리 기준 확인 필요'}] },
 { id:'system', label:'공통·시스템', icon:Settings, items:[
  {id:'approval',label:'전자결재',status:'HOLD',desc:'결재선, 대결·전결, 회수·반려 상태 기준 확인 필요'},
  {id:'authority',label:'사용자·권한',status:'HOLD',desc:'역할×법인×조직×메뉴×행위×민감도 권한표 확인 필요'},
  {id:'codes',label:'공통코드·기준정보',status:'PARTIAL',desc:'코드 목록 화면 검토용 샘플',type:'grid'},
  {id:'notices',label:'공지사항',status:'PARTIAL',desc:'공지 목록 화면 검토용 샘플',type:'grid'}] }
]
const statusText = {READY:'확정 범위 구현',PARTIAL:'부분 구현·검토용',HOLD:'정책 확인 필요',UNKNOWN:'기준 확인 필요',TODO:'2차 개발 대상'}
const sampleRows = {
 employee:[['DF-0001','샘플 임직원 A','본사','재직'],['DF-0002','샘플 임직원 B','공장','재직'],['DF-0003','샘플 임직원 C','본사','검토용']],
 'attendance-status':[['2026-10-01','샘플 임직원 A','정상','샘플 데이터'],['2026-10-02','샘플 임직원 B','확인 필요','샘플 데이터'],['2026-10-03','샘플 임직원 C','미확정','샘플 데이터']],
 codes:[['HR-001','조직유형','샘플 코드','검토용'],['HR-002','근무유형','샘플 코드','검토용']],
 notices:[['N-001','테스트 서버 검증 안내','등록 예시','검토용'],['N-002','정책 협의 항목 확인','등록 예시','검토용']]
}
function App(){
 const [active,setActive]=useState('dashboard'); const [expanded,setExpanded]=useState(['home','people','attendance','payroll','performance','learning','system']); const [collapsed,setCollapsed]=useState(false); const [query,setQuery]=useState(''); const [tabs,setTabs]=useState([{id:'dashboard',label:'HR 대시보드'}]); const [notice,setNotice]=useState(null); const [showAlerts,setShowAlerts]=useState(false)
 const allItems=useMemo(()=>groups.flatMap(g=>g.items.map(i=>({...i,group:g.label,groupId:g.id}))),[])
 const current=active==='policy-register'?{id:'policy-register',label:'정책 확인 목록',group:'공통·시스템',groupId:'system',status:'PARTIAL',desc:'고객사 협의 및 2차 개발을 위해 확인할 정책 목록'}:(allItems.find(i=>i.id===active)||allItems[0])
 const filtered=allItems.filter(i=>(i.label+' '+i.group+' '+i.desc).toLowerCase().includes(query.toLowerCase()))
 function openItem(item){setActive(item.id);setTabs(prev=>prev.some(t=>t.id===item.id)?prev:[...prev,{id:item.id,label:item.label}]); if(item.status==='HOLD'||item.status==='UNKNOWN'||item.status==='TODO')setNotice(item);}
 function toggleGroup(id){setExpanded(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id])}
 function closeTab(id){if(id==='dashboard')return;const next=tabs.filter(t=>t.id!==id);setTabs(next);if(active===id)setActive(next[next.length-1]?.id||'dashboard')}
 const isPolicy=['HOLD','UNKNOWN','TODO'].includes(current.status)
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><div className="brand-mark">大</div><div><b>대한제분 HR</b><small>PEOPLE & WORKPLACE</small></div></div><button className="icon-button mobile-menu" onClick={()=>setCollapsed(!collapsed)}><MenuIcon size={20}/></button><nav className="topnav">{groups.slice(0,6).map(g=><button key={g.id} className={current.groupId===g.id?'topnav-active':''} onClick={()=>{setExpanded(p=>p.includes(g.id)?p:[...p,g.id]);openItem(g.items[0])}}>{g.label}</button>)}</nav><div className="top-actions"><label className="global-search"><Search size={16}/><input placeholder="메뉴·업무 검색" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')}><X size={14}/></button>}</label><button className="icon-button" title="알림" onClick={()=>setShowAlerts(!showAlerts)}><Bell size={19}/><i className="notification-dot"/></button><div className="profile"><div className="avatar">HR</div><div><b>테스트 사용자</b><small>대한제분 · 검증 계정</small></div><ChevronDown size={15}/></div></div></header>
  {showAlerts&&<div className="alerts-pop"><b>알림</b><p>1차 검증 프로토타입입니다.</p><p>정책 미확정 메뉴는 안내 메시지를 표시합니다.</p></div>}
  <div className="body-layout"><aside className={`sidebar ${collapsed?'sidebar-collapsed':''}`}><div className="side-head"><span>업무 메뉴</span><button className="icon-button small" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={17}/>:<PanelLeftClose size={17}/>}</button></div>{query?<div className="search-results"><small>검색 결과 {filtered.length}건</small>{filtered.map(i=><button key={i.id} onClick={()=>openItem(i)}><span>{i.label}</span><ChevronRight size={14}/></button>)}</div>:groups.map(g=>{const Icon=g.icon;return <section className="menu-group" key={g.id}><button className="group-button" onClick={()=>toggleGroup(g.id)}><Icon size={17}/>{!collapsed&&<><span>{g.label}</span>{expanded.includes(g.id)?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</>}</button>{!collapsed&&expanded.includes(g.id)&&<div className="submenus">{g.items.map(i=><button key={i.id} className={`submenu ${active===i.id?'submenu-active':''}`} onClick={()=>openItem({...i,group:g.label,groupId:g.id})}><span>{i.label}</span>{i.status==='HOLD'||i.status==='UNKNOWN'?<i className="status-dot hold-dot"/>:i.status==='PARTIAL'?<i className="status-dot partial-dot"/>:null}</button>)}</div>}</section>})}<div className="sidebar-footer"><CircleHelp size={15}/>{!collapsed&&<span>1차 검증용 · 정책 협의 전</span>}</div></aside>
  <main className="main-area"><div className="breadcrumb"><span>대한제분 HR</span><ChevronRight size={13}/><span>{current.group||'홈'}</span><ChevronRight size={13}/><b>{current.label}</b><span className="prototype-chip">1차 검증용</span></div><div className="mdibar">{tabs.map(t=><div key={t.id} className={`mdi-tab ${active===t.id?'mdi-active':''}`}><button onClick={()=>setActive(t.id)}>{t.label}</button>{t.id!=='dashboard'&&<button className="tab-close" onClick={()=>closeTab(t.id)} aria-label={`${t.label} 닫기`}><X size={13}/></button>}</div>)}</div>
   {active==='dashboard'?<Dashboard openItem={openItem} allItems={allItems}/>:active==='policy-register'?<PolicyRegister allItems={allItems} openItem={openItem}/>:isPolicy?<PolicyPage item={current} onAlert={()=>setNotice(current)}/>:<DataPage item={current}/>}
   <footer className="main-footer"><span>대한제분 HR · 1차 고객 검증 프로토타입</span><span>실제 인사·급여 데이터 미연결 · 업무 처리/저장 미지원</span></footer>
  </main></div>
  {notice&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setNotice(null)}}><div className="policy-modal" role="dialog" aria-modal="true" aria-labelledby="policy-title"><div className="modal-icon"><AlertTriangle size={24}/></div><button className="modal-x" onClick={()=>setNotice(null)}><X size={18}/></button><h2 id="policy-title">정책 확인 필요</h2><p className="modal-lead">{notice.label}</p><p className="modal-copy">{notice.desc}</p><div className="modal-note"><b>현재 상태: {statusText[notice.status]||notice.status}</b><span>인계자료에서 확정 근거를 확인하지 못했거나 고객사 결정이 필요한 항목입니다. 임의 기준으로 업무를 처리하지 않습니다.</span></div><div className="modal-actions"><button className="btn-secondary" onClick={()=>setNotice(null)}>닫기</button><button className="btn-primary" onClick={()=>{setNotice(null);setActive('policy-register');setTabs(p=>p.some(t=>t.id==='policy-register')?p:[...p,{id:'policy-register',label:'정책 확인 목록'}])}}>정책 확인 목록 보기 <ArrowUpRight size={15}/></button></div></div></div>}
 </div>
}
function Dashboard({openItem,allItems}){const hold=allItems.filter(i=>['HOLD','UNKNOWN'].includes(i.status));return <div className="page-content"><section className="welcome-card"><div><div className="eyebrow">DAEHAN FLOUR · HR PREVIEW</div><h1>안녕하세요, 테스트 사용자님</h1><p>대한제분 HR 1차 검증 화면입니다. 메뉴와 업무 흐름을 확인하고 고객사 정책 협의 항목을 정리할 수 있습니다.</p><div className="welcome-actions"><button className="btn-primary" onClick={()=>openItem(allItems.find(i=>i.id==='employee'))}>인사 메뉴 확인 <ArrowUpRight size={16}/></button><button className="btn-outline-light" onClick={()=>openItem(allItems.find(i=>i.id==='leave'))}>정책 확인이 필요한 메뉴</button></div></div><div className="welcome-illustration"><div className="circle-orbit orbit-one"/><div className="circle-orbit orbit-two"/><div className="person-card"><Users size={26}/><b>People</b><span>First review</span></div></div></section>
 <div className="section-heading"><div><h2>검증 현황</h2><p>아래 수치는 현재 프로토타입 메뉴 분류 기준입니다.</p></div><span className="subtle-label">업무 데이터 미연결</span></div><div className="stat-grid"><Stat icon={CheckCircle2} label="화면 검토용" value={allItems.filter(i=>i.status==='PARTIAL').length} note="샘플 화면 제공"/><Stat icon={AlertTriangle} label="정책 확인 필요" value={hold.length} note="HOLD / UNKNOWN"/><Stat icon={LockKeyhole} label="실제 처리 기능" value="0" note="운영 업무 미실행"/><Stat icon={FileText} label="메뉴 후보" value={allItems.length} note="고객사와 트리 확정 필요"/></div>
 <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h3>빠른 메뉴</h3><p>고객사 협의 시 먼저 확인할 화면</p></div><span className="panel-kicker">QUICK ACCESS</span></div><div className="quick-grid">{[{id:'employee',icon:Users,label:'임직원 기본정보'},{id:'attendance-status',icon:CalendarDays,label:'근태현황 조회'},{id:'leave',icon:Clock3,label:'연차·휴가 관리'},{id:'payroll-calc',icon:Wallet,label:'급여 계산·마감'}].map(q=>{const I=q.icon;return <button key={q.id} className="quick-item" onClick={()=>openItem(allItems.find(i=>i.id===q.id))}><span><I size={19}/></span><b>{q.label}</b><ChevronRight size={14}/></button>})}</div></section><section className="panel"><div className="panel-head"><div><h3>정책 확인 목록</h3><p>고객사 협의가 필요한 대표 항목</p></div><span className="panel-kicker">OPEN ITEMS</span></div><div className="open-list">{allItems.filter(i=>['HOLD','UNKNOWN'].includes(i.status)).slice(0,5).map(i=><button key={i.id} onClick={()=>openItem(i)}><span className="open-bullet"><AlertTriangle size={14}/></span><span className="open-text"><b>{i.label}</b><small>{i.desc}</small></span><ChevronRight size={15}/></button>)}</div></section></div>
 <section className="notice-banner"><div className="notice-icon"><AlertTriangle size={20}/></div><div><b>테스트 데이터 및 기능 제한 안내</b><p>화면 내 예시 정보는 검토용 샘플이며 실제 임직원 정보가 아닙니다. 급여 계산, 근태 마감, 연차 Formula 및 실제 승인·저장 기능은 정책과 보안 기준이 확정되기 전까지 실행되지 않습니다.</p></div></section></div>}

function PolicyRegister({allItems,openItem}){const items=allItems.filter(i=>['HOLD','UNKNOWN','TODO'].includes(i.status));return <div className="page-content"><div className="page-title-row"><div><div className="eyebrow">POLICY REGISTER</div><h1>정책 확인 목록</h1><p>고객사 협의 전 확인이 필요한 메뉴별 항목입니다. 이 목록은 개발 인계자료 기준의 1차 후보이며 최종 정책 목록은 아닙니다.</p></div><span className="status-pill status-hold"><AlertTriangle size={14}/>{items.length}개 확인 대상</span></div><div className="panel table-panel"><div className="panel-head"><div><h3>메뉴별 확인 필요 항목</h3><p>행을 선택하면 해당 메뉴의 확인 내용을 볼 수 있습니다.</p></div></div><div className="table-wrap"><table><thead><tr><th>메뉴</th><th>현재 상태</th><th>확인 필요 사항</th><th>이동</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.group} / {i.label}</td><td><span className="status-pill status-hold">{statusText[i.status]}</span></td><td>{i.desc}</td><td><button className="btn-light" onClick={()=>openItem(i)}>확인</button></td></tr>)}</tbody></table></div><div className="sample-watermark"><AlertTriangle size={15}/> 정책 미확정 항목은 임의 Formula/상태를 적용하지 않습니다.</div></div></div>}
function Stat({icon:Icon,label,value,note}){return <div className="stat-card"><div className="stat-top"><span>{label}</span><Icon size={18}/></div><div className="stat-value">{value}</div><small>{note}</small></div>}
function PolicyPage({item}){return <div className="page-content"><div className="page-title-row"><div><div className="eyebrow">POLICY REVIEW</div><h1>{item.label}</h1><p>{item.group} · 정책 및 업무 기준 확인 대상</p></div><span className="status-pill status-hold"><AlertTriangle size={14}/>{statusText[item.status]}</span></div><div className="policy-hero"><div className="policy-hero-icon"><LockKeyhole size={26}/></div><div><h2>정책 확인 후 2차 개발 대상</h2><p>{item.desc}</p><p>현재는 고객 협의 전 단계이므로 업무 계산·마감·실제 반영을 수행하지 않습니다.</p></div></div><div className="panel policy-detail"><h3>고객사 협의 항목</h3><div className="question-row"><span>01</span><div><b>업무 기준 / 정책</b><p>해당 메뉴에서 적용해야 할 대한제분 고유 규칙과 예외 조건을 확인해야 합니다.</p></div><span className="status-pill status-hold">미확정</span></div><div className="question-row"><span>02</span><div><b>Formula / 상태 전이</b><p>산식, 상태값, 승인 조건이 자료에 없으면 개발자가 임의로 결정하지 않습니다.</p></div><span className="status-pill status-hold">미확정</span></div><div className="question-row"><span>03</span><div><b>권한 및 감사 이력</b><p>역할·법인·조직·행위·민감도에 따른 접근 범위와 감사 이력을 확인해야 합니다.</p></div><span className="status-pill status-hold">확인 필요</span></div></div><div className="panel"><div className="panel-head"><div><h3>확인 결과 기록</h3><p>현재 프로토타입에서는 기록을 저장하지 않습니다. 협의 후 별도 정책확인표에 반영해 주세요.</p></div></div><div className="read-only-note"><FileText size={18}/><span>이 화면은 정책 협의용입니다. 입력/저장 API는 연결되어 있지 않습니다.</span></div></div></div>}
function DataPage({item}){const rows=sampleRows[item.id]||[['—','샘플 화면','정책 확인 전','검토용']];const [term,setTerm]=useState('');return <div className="page-content"><div className="page-title-row"><div><div className="eyebrow">SCREEN PREVIEW</div><h1>{item.label}</h1><p>{item.desc}</p></div><span className="status-pill status-partial"><CheckCircle2 size={14}/>{statusText[item.status]}</span></div><div className="panel search-panel"><div className="form-grid"><label>조회 기준일<input type="date" defaultValue="2026-10-09"/></label><label>구분<select defaultValue="all"><option value="all">전체</option><option>검토용</option></select></label><label className="keyword-field">검색어<input value={term} onChange={e=>setTerm(e.target.value)} placeholder="검색어 입력"/></label><button className="btn-primary" onClick={()=>{}}>조회</button><button className="btn-light" onClick={()=>setTerm('')}>초기화</button></div></div><div className="panel table-panel"><div className="panel-head"><div><h3>{item.label} 목록</h3><p>화면 배치 및 조회 조건 확인용 샘플 데이터입니다.</p></div><div className="table-actions"><button className="btn-light" onClick={()=>window.alert('정책 확인 필요: 저장 기능은 2차 개발 대상입니다.')}>저장</button><button className="btn-light" onClick={()=>window.alert('정책 확인 필요: 엑셀 다운로드 권한 및 데이터 범위 확인이 필요합니다.')}>엑셀 다운로드</button></div></div><div className="table-wrap"><table><thead><tr><th>No.</th><th>코드 / 일자</th><th>명칭</th><th>구분</th><th>상태</th></tr></thead><tbody>{rows.filter(r=>r.join(' ').toLowerCase().includes(term.toLowerCase())).map((r,i)=><tr key={i}><td>{String(i+1).padStart(2,'0')}</td>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div><div className="sample-watermark"><AlertTriangle size={15}/> 샘플 데이터 · 실제 DB/API 미연결 · 변경사항 저장 불가</div></div><div className="notice-banner"><div className="notice-icon"><CircleHelp size={20}/></div><div><b>화면 검토 시 확인해 주세요</b><p>항목명, 검색조건, 상태표시, 목록 컬럼, 버튼 위치가 대한제분 업무에 적합한지 확인해 주세요. 업무 규칙 또는 실제 데이터 처리가 필요한 경우 정책 확정 후 2차 개발합니다.</p></div></div></div>}

createRoot(document.getElementById('root')).render(<App/>)
